### ISSUE TITLE
Config to disable backup on startup?

### ISSUE THREAD

**Issue by xJon** [Silly511/Backups-Mod#10]
The mod works great, but I wish there could be a config option to disable the startup backup, whenever I enter a new world.
Thanks!

**Comment by Fadenfire** [comment]
I'm really sorry it took me so long to reply, I got the notification while I was on vacation and then completely forgot when I got back home.

There's a config option called `backupInterval` that if you set to zero, automatic backups will be disabled. There isn't currently a way to disable only the startup backups and not the timed backups, I might add a config option for that.

**Comment by xJon** [comment]
I do want the automatic backups, just I thought an option to disable the startup backups would be nice.
Thanks!

**Comment by Fadenfire** [comment]
I added a config option to disable startup backups in version 1.4.8.

**Comment by xJon** [comment]
Thank you!
May I ask what is the main purpose of startup backups?

**Comment by Fadenfire** [comment]
I'm actually not really sure why I added them. I think it was because if you quit the world right before a backup and started the world again it would be awhile before a backup happened again. I might change it in a later update so that backups are based on world time so that the backup timer isn't reset between world saves.

**Comment by xJon** [comment]
That'd be quite clever. Thank you for the support nonetheless!

**Comment by xJon** [comment]
Hey, I've updated to the latest version of the mod and set `B:backupOnWorldStart=false`, yet the backups still happen when I enter a new SSP world?

**Comment by Fadenfire** [comment]
I think that's a bug, however in the next update the backup timer will be saved with the world so that config option will be removed.

**Comment by xJon** [comment]
👍
