### ISSUE TITLE
Backups button does not appear when OpenTerrainGenerator is loaded

### ISSUE THREAD

**Issue by floral-qua-floral** [Silly511/Backups-Mod#12]
When loaded alongside [OpenTerrainGenerator](https://www.curseforge.com/minecraft/mc-mods/open-terrain-generator), Backups is unable to insert the Backups button into the world select screen. This is because OTG removes the Edit World and Recreate World buttons from the world select GUI. Backup functionality still seems perfectly functional, however the most convenient means of accessing backups is rendered inaccessible by this change, severely impacting this mod's usability - as far as I can tell, features like the ability to enter backups are effectively removed by the conflict.

**Comment by Fadenfire** [comment]
I fixed this a while back but it seems an update to OTG broke it again. It should be fixed now in version 1.4.9.
