### ISSUE TITLE
Set maximum number of backups?

### ISSUE THREAD

**Issue by spiral6** [Silly511/Backups-Mod#14]
Hi. I like the mod, it works pretty well and has saved my server from losing data when it crashes for some reason I'm unable to discern. 

That being said, my server doesn't have much space allocated towards it. As a result, I'm unable to save a lot of backups. Is there anyway the mod can automatically delete backups if they are older than a certain time/date or just have a maximum number of backups set so that the oldest one that exceeds the number gets deleted?

**Comment by Fadenfire** [comment]
In version 1.5.0 I've added a config option to set the maximum number of days old a backup can be before it's deleted.

**Comment by spiral6** [comment]
That is not the same thing and doesn't fulfill the request that I stated.

There could be multiple backups in that day that I'd like to keep, but erasing the oldest ones. I could want the server to back up every 5 min but erase every backup older than 30 min.

**Comment by Fadenfire** [comment]
Oh I didn't know you wanted to keep so few backups. Next update I'll add a config option to keep a maximum number of backups.

**Comment by Fadenfire** [comment]
Added in version 1.5.1.
