### ISSUE TITLE
Save backups in 24h format.

### ISSUE THREAD

**Issue by spiral6** [Silly511/Backups-Mod#15]
At the current moment, backups are saved in DD-MM-YYYY 12h format, which is unfortunate because they aren't in alphabetical order that way and makes the order feel disorganized. I propose, for the sake of simplicity and ease for the server admin, that backups be saved in 24h format without an AM or PM displayed, at least as a config option.

**Comment by Fadenfire** [comment]
In version 1.5.1 the format is now `year-month-day hour-minute-second` with `hour` in 24-hour time, so the backups should now be properly alphabetized by date. I'm not sure why I was using that other format.
