### ISSUE TITLE
Documentation on Curseforge does not match ingame command syntax

### ISSUE THREAD

**Issue by morerokk** [Silly511/Backups-Mod#16]
The Curseforge page for this mod says that to restore a world backup, you have to run `/bm restoreworld`. This appears to be false, as this command does not exist. It is actually `/bm serverrestore`.

The page also says that you can restore backups in the same manner as they are listed with `/bm listbackups`. This is also false. `/bm listbackups` puts a *space* between the date and time, when you're actually supposed to use a *dash* in the `/bm serverrestore` command. The only way I was able to find this out is by looking into the source code.

Please update the documentation accordingly, and fix the way `/bm listbackups` returns the names.

**Comment by Fadenfire** [comment]
I think you're using an older version, because I changed `/bm serverrestore` to `/bm restoreworld` in version 1.5.0.

You're right that the format shown in `/bm listbackups` isn't the same as what's accepted by the restore commands, I'll fix that in the next update.

**Comment by Fadenfire** [comment]
Fixed in version 1.5.2.
