### ISSUE TITLE
Restoring a backup on a server

### ISSUE THREAD

**Issue by xJon** [Silly511/Backups-Mod#17]
Not sure if I understood it correctly.
To restore a backup one would need to launch the server and run this command?
`/bm restoreworld <backup>`
What would one do if the server cannot start due to a corrupted worlds?
Thank you!

**Comment by Fadenfire** [comment]
You can use that command in game or you can use this command on your computer's command line: ` java -jar <path to mod file> <backup dir> <world dir>`. That'll restore the backup in backup dir to world dir.

**Comment by xJon** [comment]
I just noticed it was already written in CurseForge. Thanks!
