### ISSUE TITLE
Question - Can you force a backup with a different main folder?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Silly511/Backups-Mod#2]
I often test mods and I am tired of losing worlds. Is this capable of creating main branch backups at user request or is all functions of this mod automatic?

**Comment by Fadenfire** [comment]
You can do `/backup` to start a backup, but all backups go to the same directory. If you don't want any automatic backups then you can set `backupInterval` to zero in the config. You can also change the path to the backups directory in the config.
