### ISSUE TITLE
Command to restore world backup error with 1.5.2

### ISSUE THREAD

**Issue by xJon** [Silly511/Backups-Mod#22]
It still seems to generate the backup, and the error does not appear if the `world dir` is already present.
![Screenshot_3](https://user-images.githubusercontent.com/8945347/72944165-d2cd4e80-3d80-11ea-8e8b-79359f5eecf8.png)
Note that this doesn't have anything to do with #20 or #21, and did not happen with `1.5.1`.

**Comment by Fadenfire** [comment]
That's a bug, I'll release a new version fixing it soon.

**Comment by Fadenfire** [comment]
Fixed in version 1.5.3.
