### ISSUE TITLE
Backup failed?

### ISSUE THREAD

**Issue by xJon** [Silly511/Backups-Mod#24]
A [player reported](https://github.com/xJon/The-1.12.2-Pack/issues/227
) backup failing due to space in the backups path?
> https://paste.ubuntu.com/p/M3SmDth4wm/

**Comment by Fadenfire** [comment]
I think the file that stores a reference to the last backup is somehow corrupted so that it contains only spaces. Tell the person that opened the issue to try deleting the file `backups\REDRED\Last`.

**Comment by xJon** [comment]
That fixed it.
Do you know why it happened?

**Comment by Fadenfire** [comment]
No, I have no idea why that happened. In the next update I'll try to make it so the backup doesn't fail if the last backup file is corrupted, so that'll help.
