### ISSUE TITLE
Crashes on loading into backup world

### ISSUE THREAD

**Issue by Noro149** [Silly511/Backups-Mod#25]
when trying to load into a backup i get this crash

https://paste.dimdev.org/fasitudela.mccrash

**Comment by Fadenfire** [comment]
Does it crash every time you load the backup? Is it only that specific backup or does it happen with all backups?

**Comment by Noro149** [comment]
Yes it crashes with every backup of that world. When I try to load a backup the first time it gives me a crash and if I attempt to load it again it gives me a different type of crash. I'll try to get a crash log of both attempts.

**Comment by Fadenfire** [comment]
Fixed in version 1.5.6.
