### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by mateuszdevs** [Silly511/Backups-Mod#28]
I have been using this mod for about a week now and ive noticed recently that after every backup the memory keeps rising up and isnt being cleared. Usually the server sits around 3gb but after 2 backup cycles it will max out the memory at 6gb (which is how much the server is allowed up to). 

Im assuming during every backup cycle the world gets saved to ram then gets saved onto the disk from the ram. (saying that i dont know much java just guessing how it works). I was wondering if this memory usage is intended and there isnt a way to clean up the loaded memory from the mod after a backup is done since this gives the server a hard time and GC doesnt clear it.

**Comment by Fadenfire** [comment]
I can't replicate this myself, but it may have to do with a specific mod you have installed or the size of the world. Try switching to using [this backup mod](https://www.curseforge.com/minecraft/mc-mods/aromabackup) for a little while and see if the high memory persists. If it does the same thing then it's either minecraft itself or some other mod.

**Comment by mateuszdevs** [comment]
Sorry for the late reply. Aroma backup has the same memory issue so like you said it is probably the world size or a different mod.
