### ISSUE TITLE
Command blocks unable to run /backup

### ISSUE THREAD

**Issue by edwardg117** [Silly511/Backups-Mod#3]
Command blocks are unable to run the /backup command, the following error is given:
> "You do not have permission to use this command"

Attempting to use execute like so:
> execute @p ~ ~ ~ backup

produces:
> "Failed to execute 'backup' as edwardg"

Running the command normally though chat works as intended. Not sure why a command block is having trouble.

**Comment by Fadenfire** [comment]
This because I set the permission level for the /backup command to 3, I'm going to change it back to 2 in the next update.

**Comment by Fadenfire** [comment]
Fixed in 1.4.
