### ISSUE TITLE
Difficulties Restoring Backup [Older Backup Version 1.4.5]

### ISSUE THREAD

**Issue by CanadianHarp85** [Silly511/Backups-Mod#31]
I only have the options of "Usage: /backupsmod <backup|lastbackup|restore> ..." no option for restoring the world. I've tried to use restoreworld, restore world, restoreWorld to no avail. I have tried this as a player and from console. Also /bm restoreworld is not recognized, since I assume in my version it hadn't yet been implemented. What is the right way to go about restoring a server backup?

Using Backups-1.12.2-1.4.5.jar

World is currently in a state that requires backup.

Is it safe to update and attempt restore after?

My apologies if this shouldn't be posted here.
Posted on the Curse page as well as I wasn't sure what the preference would be. Name is Sniper_Gecko there.

**Comment by Fadenfire** [comment]
You should be able update to the latest version without any problems.
