### ISSUE TITLE
Error loading backup

### ISSUE THREAD

**Issue by xXKillSTrEAkXx** [Silly511/Backups-Mod#34]
So im playing a modpack called 1.12.2 pack and im using your mod to do backups, im running a server and im trying to use the command to restore de last backup and it says "backup is invalid" the backup files are intact is there anyway to solve this problem ? and is there a way to apply the backup manually ? (ive seen the backups and the files are all zipped one by one).

**Comment by Fadenfire** [comment]
Can you upload the server logs?
