### ISSUE TITLE
Restore backups from linux

### ISSUE THREAD

**Issue by 8-BrickDMG** [Silly511/Backups-Mod#4]
Any chance we could restore backups in a linux environment? Correct me if I'm wrong but I've been copying the contents from a backup folder into a new world folder manually, only to have the server crash on me.

Is this not the right way to do so?

**Comment by Fadenfire** [comment]
There currently isn't a way to restore backups on a server, however I'm adding a way to do so in the next update. The reason you can't just copy the files over is because they are compressed.

**Comment by 8-BrickDMG** [comment]
What could a workaround for the time being be? I have multiple backups on the server currently and only tried it for the first time today.

**Comment by Fadenfire** [comment]
I suggest you just wait for version 1.4, I should release it in the next couple of days.

**Comment by Fadenfire** [comment]
I just released version 1.4, you can now restore backups from the command line with `java -jar <path to the mod file> <path to backup dir> <path to world dir>`.
