### ISSUE TITLE
store in zip archive

### ISSUE THREAD

**Issue by Quetz4l** [Silly511/Backups-Mod#44]
Store without archive is bad for hdd and ssd. There are so many small files...

Add storing in zip or another archive

**Comment by Fadenfire** [comment]
Unfortunately, storing all of the backup files in a single archive file would prevent my mod from creating incremental backups, which is the central feature of my mod. My mod uses [hard links](https://en.wikipedia.org/wiki/Hard_link) to prevent unchanged files from taking up additional space across multiple backups. Most archive formats do not support hard links, and the few that do (like tar) cannot form hard links across separate archives.

If you want a backup mod that does store everything in archive files, I suggest looking at something like [FTB Backups](https://www.curseforge.com/minecraft/mc-mods/ftb-backups-forge).
