### ISSUE TITLE
Crash on server startup with v1.4.1

### ISSUE THREAD

**Issue by 8-BrickDMG** [Silly511/Backups-Mod#5]
[crash-2018-09-27_02.00.08-server.txt](https://github.com/Silly511/Backups-Mod/files/2421958/crash-2018-09-27_02.00.08-server.txt)

**Comment by Fadenfire** [comment]
Yeah, I just discovered this crash. For some reason servers don't come with the apache compress library. I'll try to release an update tomorrow.

**Comment by Fadenfire** [comment]
Fixed in 1.4.2.
