### ISSUE TITLE
game crash while loading nod

### ISSUE THREAD

**Issue by voidegg** [Silly511/Backups-Mod#6]
i install this mod on a world that don't have this mod before and my game crash

java.lang.ArrayIndexOutOfBoundsException: 3
    at silly511.backups.BackupManager.restoreSaving(BackupManager.java:141)
    at silly511.backups.BackupManager.serverTick(BackupManager.java:56)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_21_BackupManager_serverTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 700497392 bytes (668 MB) / 2712666112 bytes (2587 MB) up to 2863661056 bytes (2731 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
  FML: MCP 9.42 Powered by Forge 14.23.5.2769 164 mods loaded, 164 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State     | ID                                           | Version                  | Source                                             | Signature                                |
       |:--------- |:-------------------------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | UCHIJAAAA | minecraft                                    | 1.12.2                   | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | mcp                                          | 9.42                     | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.5.2769.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAA | forge                                        | 14.23.5.2769             | forge-1.12.2-14.23.5.2769.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAA | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | openmodscore                                 | 0.12.1                   | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | foamfixcore                                  | 7.7.4                    | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | elucore                                      | 1.0                      | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | uncraftingtable                              | 1.8-beta6                | [1.12]UncraftingTable-1.8-beta6.jar                | None                                     |
       | UCHIJAAAA | fastbench                                    | 1.5.3                    | FastWorkbench-1.12.2-1.5.3.jar                     | None                                     |
       | UCHIJAAAA | actuallyadditions                            | 1.12.2-r141              | ActuallyAdditions-1.12.2-r141.jar                  | None                                     |
       | UCHIJAAAA | baubles                                      | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
       | UCHIJAAAA | actuallybaubles                              | 1.1                      | ActuallyBaubles-1.12-1.1.jar                       | None                                     |
       | UCHIJAAAA | akashictome                                  | 1.2-10                   | AkashicTome-1.2-10.jar                             | None                                     |
       | UCHIJAAAA | applecore                                    | 3.1.4                    | AppleCore-mc1.12.2-3.1.4.jar                       | None                                     |
       | UCHIJAAAA | crafttweaker                                 | 4.1.11                   | CraftTweaker2-1.12-4.1.11.jar                      | None                                     |
       | UCHIJAAAA | mtlib                                        | 3.0.5                    | MTLib-3.0.5.jar                                    | None                                     |
       | UCHIJAAAA | modtweaker                                   | 4.0.13                   | modtweaker-4.0.14.jar                              | None                                     |
       | UCHIJAAAA | jei                                          | 4.12.1.217               | jei_1.12.2-4.12.1.217.jar                          | None                                     |
       | UCHIJAAAA | appleskin                                    | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | UCHIJAAAA | aroma1997core                                | 2.0.0.0                  | Aroma1997Core-1.12.2-2.0.0.0.jar                   | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | UCHIJAAAA | aroma1997sdimension                          | 1.3.0.0.b37              | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar  | None                                     |
       | UCHIJAAAA | aromabackup                                  | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                     | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | UCHIJAAAA | aromabackuprecovery                          | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                     | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | UCHIJAAAA | morphtool                                    | 1.2-16                   | Morph-o-Tool-1.2-16.jar                            | None                                     |
       | UCHIJAAAA | quark                                        | r1.5-130                 | Quark-r1.5-130.jar                                 | None                                     |
       | UCHIJAAAA | autoreglib                                   | 1.3-20                   | AutoRegLib-1.3-20.jar                              | None                                     |
       | UCHIJAAAA | codechickenlib                               | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | avaritia                                     | 3.2.0                    | Avaritia-1.12.2-3.2.0.25-universal.jar             | None                                     |
       | UCHIJAAAA | avaritiatweaks                               | 1.12.2-1.1               | AvaritiaTweaks-1.12.2-1.1.jar                      | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
       | UCHIJAAAA | backups                                      | 1.4.2                    | Backups-1.12.2-1.4.2.jar                           | None                                     |
       | UCHIJAAAA | betterbuilderswands                          | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar    | None                                     |
       | UCHIJAAAA | biomesoplenty                                | 7.0.1.2399               | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar      | None                                     |
       | UCHIJAAAA | blockcraftery                                | 0.1.3                    | blockcraftery-0.1.3.jar                            | None                                     |
       | UCHIJAAAA | cyclicmagic                                  | 1.17.3                   | Cyclic-1.12.2-1.17.3.jar                           | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
       | UCHIJAAAA | guideapi                                     | 1.12-2.1.6-61            | Guide-API-1.12-2.1.6-61.jar                        | None                                     |
       | UCHIJAAAA | bloodmagic                                   | 1.12.2-2.3.3-101         | BloodMagic-1.12.2-2.3.3-101.jar                    | None                                     |
       | UCHIJAAAA | bonsaitrees                                  | 1.0.5                    | bonsaitrees-1.0.5-b77.jar                          | None                                     |
       | UCHIJAAAA | bookshelf                                    | 2.3.559                  | Bookshelf-1.12.2-2.3.559.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAA | redstoneflux                                 | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | cofhcore                                     | 4.6.1                    | CoFHCore-1.12.2-4.6.1.22-universal.jar             | None                                     |
       | UCHIJAAAA | boptools                                     | 0.0.3                    | boptools-1.12-0.0.3.0.jar                          | None                                     |
       | UCHIJAAAA | brandonscore                                 | 2.4.5                    | BrandonsCore-1.12.2-2.4.5.176-universal.jar        | None                                     |
       | UCHIJAAAA | buildinggadgets                              | 2.3.6                    | BuildingGadgets-2.3.6.jar                          | None                                     |
       | UCHIJAAAA | carryon                                      | 1.11.1                   | CarryOn MC1.12.2 v1.11.1.jar                       | None                                     |
       | UCHIJAAAA | chameleon                                    | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | UCHIJAAAA | chancecubes                                  | 1.12.2-3.2.2.237         | ChanceCubes-1.12.2-3.2.2.237.jar                   | None                                     |
       | UCHIJAAAA | chickens                                     | 6.0.4                    | chickens-6.0.4.jar                                 | None                                     |
       | UCHIJAAAA | ctm                                          | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                          | None                                     |
       | UCHIJAAAA | chisel                                       | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
       | UCHIJAAAA | cofhworld                                    | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | storagedrawers                               | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                    | None                                     |
       | UCHIJAAAA | compactdrawers                               | 1.12.2-1.0.3.86          | CompactDrawers-1.12.2-1.0.3.86.jar                 | None                                     |
       | UCHIJAAAA | controlling                                  | 3.0.6                    | Controlling-3.0.6.jar                              | None                                     |
       | UCHIJAAAA | cookingforblockheads                         | 6.4.65                   | CookingForBlockheads_1.12.2-6.4.65.jar             | None                                     |
       | UCHIJAAAA | cosmeticarmorreworked                        | 1.12.2-v3                | CosmeticArmorReworked-1.12.2-v3.jar                | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | UCHIJAAAA | cosmeticarmorreworked|tombmanygraves         | 1.12.2-v3                | CosmeticArmorReworked-1.12.2-v3.jar                | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | UCHIJAAAA | craftingtweaks                               | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                    | None                                     |
       | UCHIJAAAA | ctgui                                        | 1.0.0                    | CraftTweaker2-1.12-4.1.11.jar                      | None                                     |
       | UCHIJAAAA | crafttweakerjei                              | 2.0.2                    | CraftTweaker2-1.12-4.1.11.jar                      | None                                     |
       | UCHIJAAAA | cucumber                                     | 1.1.1                    | Cucumber-1.12.2-1.1.1.jar                          | None                                     |
       | UCHIJAAAA | cyberware                                    | 0.2.10.15                | cyberware-1.12.2-0.2.10.15.jar                     | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
       | UCHIJAAAA | endercore                                    | 1.12.2-0.5.41            | EnderCore-1.12.2-0.5.41.jar                        | None                                     |
       | UCHIJAAAA | thermalfoundation                            | 2.6.1                    | ThermalFoundation-1.12.2-2.6.1.22-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | draconicevolution                            | 2.3.15                   | Draconic-Evolution-1.12.2-2.3.15.312-universal.jar | None                                     |
       | UCHIJAAAA | thermalexpansion                             | 5.5.2                    | ThermalExpansion-1.12.2-5.5.2.39-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | enderio                                      | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                          | None                                     |
       | UCHIJAAAA | mantle                                       | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                           | None                                     |
       | UCHIJAAAA | enderiointegrationtic                        | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                          | None                                     |
       | UCHIJAAAA | tconstruct                                   | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                    | None                                     |
       | UCHIJAAAA | p455w0rdslib                                 | 2.0.35                   | p455w0rdslib-1.12-2.0.35.jar                       | None                                     |
       | UCHIJAAAA | theoneprobe                                  | 1.4.24                   | theoneprobe-1.12-1.4.24.jar                        | None                                     |
       | UCHIJAAAA | danknull                                     | 1.4.43                   | DankNull-1.12-1.4.43.jar                           | None                                     |
       | UCHIJAAAA | darkutils                                    | 1.8.211                  | DarkUtils-1.12.2-1.8.211.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAA | movingworld                                  | 1.12-6.342               | movingworld-1.12-6.342-full.jar                    | None                                     |
       | UCHIJAAAA | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar                | None                                     |
       | UCHIJAAAA | endercompass                                 | 1.2.6.2                  | EnderCompass-1.12-1.2.6.2.jar                      | None                                     |
       | UCHIJAAAA | enderiobase                                  | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                          | None                                     |
       | UCHIJAAAA | enderioconduits                              | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                          | None                                     |
       | UCHIJAAAA | enderioconduitsappliedenergistics            | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                          | None                                     |
       | UCHIJAAAA | refinedstorage                               | 1.6.5                    | refinedstorage-1.6.5.jar                           | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | UCHIJAAAA | enderioconduitsopencomputers                 | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                          | None                                     |
       | UCHIJAAAA | enderioconduitsrefinedstorage                | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                          | None                                     |
       | UCHIJAAAA | enderiointegrationforestry                   | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                          | None                                     |
       | UCHIJAAAA | enderiointegrationticlate                    | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                          | None                                     |
       | UCHIJAAAA | ftblib                                       | 5.3.0.56                 | FTBLib-5.3.0.56.jar                                | None                                     |
       | UCHIJAAAA | enderiomachines                              | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                          | None                                     |
       | UCHIJAAAA | enderiopowertools                            | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                          | None                                     |
       | UCHIJAAAA | enderstorage                                 | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | valkyrielib                                  | 1.12.2-2.0.17.2          | valkyrielib-1.12.2-2.0.17.3.jar                    | None                                     |
       | UCHIJAAAA | environmentaltech                            | 1.12.2-2.0.17.1          | environmentaltech-1.12.2-2.0.17.1.jar              | None                                     |
       | UCHIJAAAA | erebus                                       | 1.0.23                   | Erebus-1.0.23.jar                                  | None                                     |
       | UCHIJAAAA | extrautils2                                  | 1.0                      | extrautils2-1.12-1.9.4.jar                         | None                                     |
       | UCHIJAAAA | fasterladderclimbing                         | 0.1-146                  | FasterLadderClimbing-1.12-0.1-146.jar              | None                                     |
       | UCHIJAAAA | fastfurnace                                  | 1.1.1                    | FastFurnace-1.12.2-1.1.1.jar                       | None                                     |
       | UCHIJAAAA | fastleafdecay                                | v14                      | FastLeafDecay-v14.jar                              | None                                     |
       | UCHIJAAAA | mekanism                                     | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                     | None                                     |
       | UCHIJAAAA | sonarcore                                    | 5.0.16                   | sonarcore-1.12.2-5.0.16-16.jar                     | None                                     |
       | UCHIJAAAA | fluxnetworks                                 | 3.0.16                   | fluxnetworks-1.12.2-3.0.16-11.jar                  | None                                     |
       | UCHIJAAAA | foamfix                                      | 0.10.2-1.12.2            | foamfix-0.10.2-1.12.2.jar                          | None                                     |
       | UCHIJAAAA | forgelin                                     | 1.7.4                    | Forgelin-1.7.4.jar                                 | None                                     |
       | UCHIJAAAA | ftbutilities                                 | 5.3.0.52                 | FTBUtilities-5.3.0.52.jar                          | None                                     |
       | UCHIJAAAA | furnaceonastick                              | 1.0                      | furnaceonastick-1.0.jar                            | None                                     |
       | UCHIJAAAA | hatchery                                     | 2.1.4                    | hatchery-1.12.2-2.1.4.jar                          | None                                     |
       | UCHIJAAAA | immersiveengineering                         | 0.12-86                  | ImmersiveEngineering-0.12-86.jar                   | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | UCHIJAAAA | immersivepetroleum                           | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar                | None                                     |
       | UCHIJAAAA | immersivetech                                | 1.3.10                   | immersivetech-1.12-1.3.10.jar                      | None                                     |
       | UCHIJAAAA | teslacorelib                                 | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAA | industrialforegoing                          | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.11.4-214.jar          | None                                     |
       | UCHIJAAAA | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UCHIJAAAA | ironbackpacks                                | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
       | UCHIJAAAA | ironchest                                    | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                    | None                                     |
       | UCHIJAAAA | ironfurnaces                                 | 1.3.1                    | ironfurnaces-1.3.1.jar                             | None                                     |
       | UCHIJAAAA | jeresources                                  | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar            | None                                     |
       | UCHIJAAAA | jeroreintegration                            | 1.1.0                    | JEROreIntegration-1.12.2-1.1.0.jar                 | None                                     |
       | UCHIJAAAA | journeymap                                   | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                        | None                                     |
       | UCHIJAAAA | mcjtylib_ng                                  | 3.0.5                    | mcjtylib-1.12-3.0.5.jar                            | None                                     |
       | UCHIJAAAA | mekanismgenerators                           | 9.4.11                   | MekanismGenerators-1.12.2-9.4.13.349.jar           | None                                     |
       | UCHIJAAAA | mekanismtools                                | 9.4.11                   | MekanismTools-1.12.2-9.4.13.349.jar                | None                                     |
       | UCHIJAAAA | mekatweaker                                  | 1.1.2                    | mekatweaker-1.12-1.1.2.jar                         | None                                     |
       | UCHIJAAAA | mob_grinding_utils                           | 0.3.11                   | MobGrindingUtils-0.3.11.jar                        | None                                     |
       | UCHIJAAAA | modnametooltip                               | 1.10.0                   | modnametooltip_1.12.2-1.10.0.jar                   | None                                     |
       | UCHIJAAAA | numina                                       | 1.10.0                   | ModularPowersuits-1.12.2-0.3.0.11.jar              | None                                     |
       | UCHIJAAAA | powersuits                                   | 1.12.2-0.3.0.11          | ModularPowersuits-1.12.2-0.3.0.11.jar              | None                                     |
       | UCHIJAAAA | morechickens                                 | 3.1.0                    | morechickens-1.12.2-3.1.0.jar                      | None                                     |
       | UCHIJAAAA | moreoverlays                                 | 1.14                     | moreoverlays-1.14-mc1.12.2.jar                     | None                                     |
       | UCHIJAAAA | mousetweaks                                  | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                       | None                                     |
       | UCHIJAAAA | mysticalagriculture                          | 1.6.13                   | MysticalAgriculture-1.12-1.6.13.jar                | None                                     |
       | UCHIJAAAA | mysticalagradditions                         | 1.2.8                    | mysticalagradditions-1.12-1.2.8.jar                | None                                     |
       | UCHIJAAAA | naturescompass                               | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                    | None                                     |
       | UCHIJAAAA | recipehandler                                | 0.12                     | NoMoreRecipeConflict-0.12(1.12.2).jar              | None                                     |
       | UCHIJAAAA | nuclearcraft                                 | 2.12d                    | NuclearCraft-2.12d--1.12.2.jar                     | None                                     |
       | UCHIJAAAA | openmods                                     | 0.12.1                   | OpenModsLib-1.12.2-0.12.1.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJAAAA | openblocks                                   | 1.8                      | OpenBlocks-1.12.2-1.8.jar                          | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJAAAA | oreexcavation                                | 1.4.129                  | OreExcavation-1.4.129.jar                          | None                                     |
       | UCHIJAAAA | harvestcraft                                 | 1.12.2z                  | Pam's HarvestCraft 1.12.2z.jar                     | None                                     |
       | UCHIJAAAA | randomthings                                 | 4.2.1.2                  | RandomThings-MC1.12.2-4.2.1.2.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UCHIJAAAA | reborncore                                   | 3.10.2.337               | RebornCore-1.12.2-3.10.2.337-universal.jar         | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | UCHIJAAAA | rebornstorage                                | 1.0.0                    | RebornStorage-1.12.2-3.2.2.65.jar                  | None                                     |
       | UCHIJAAAA | refinedstorageaddons                         | 0.4.2                    | refinedstorageaddons-0.4.2.jar                     | None                                     |
       | UCHIJAAAA | resourceloader                               | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UCHIJAAAA | rftools                                      | 7.56                     | rftools-1.12-7.56.jar                              | None                                     |
       | UCHIJAAAA | rftoolsdim                                   | 5.61                     | rftoolsdim-1.12-5.61.jar                           | None                                     |
       | UCHIJAAAA | rftoolspower                                 | 1.1.1                    | rftoolspower-1.12-1.1.1.jar                        | None                                     |
       | UCHIJAAAA | roguelike                                    | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
       | UCHIJAAAA | simplecorn                                   | 2.4.1                    | SimpleCorn1.12-1.12-2.4.1.jar                      | None                                     |
       | UCHIJAAAA | soulshardstow                                | 1.12-2.7.6-56            | SoulShards-TOW-1.12-2.7.6-56.jar                   | None                                     |
       | UCHIJAAAA | stevescarts                                  | 2.4.24.118               | StevesCarts-1.12.2-2.4.24.118.jar                  | None                                     |
       | UCHIJAAAA | supersoundmuffler                            | 1.0.2.9                  | supersoundmuffler-1.12.1-1.0.2.9.jar               | None                                     |
       | UCHIJAAAA | switchbow                                    | 1.5.4                    | switchbow-1.5.4.jar                                | None                                     |
       | UCHIJAAAA | thermalcultivation                           | 0.3.1                    | ThermalCultivation-1.12.2-0.3.1.8-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | thermaldynamics                              | 2.5.3                    | ThermalDynamics-1.12.2-2.5.3.16-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | thermalinnovation                            | 0.3.1                    | ThermalInnovation-1.12.2-0.3.1.8-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | tinker_io                                    | release 2.6.1            | tinker_io-1.12.2-release 2.6.1.jar                 | None                                     |
       | UCHIJAAAA | tinkertoolleveling                           | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar                | None                                     |
       | UCHIJAAAA | tp                                           | 3.2.31                   | tinyprogressions-1.12.2-3.3.31-Release.jar         | None                                     |
       | UCHIJAAAA | tombstone                                    | 3.2.1                    | tombstone-3.2.1-1.12.jar                           | None                                     |
       | UCHIJAAAA | universalmodifiers                           | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.17.3.jar                    | None                                     |
       | UCHIJAAAA | vanillafix                                   | 1.0.9-97                 | VanillaFix-1.0.9-97.jar                            | None                                     |
       | UCHIJAAAA | waystones                                    | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                        | None                                     |
       | UCHIJAAAA | woot                                         | 1.12.2-1.4.5             | woot-1.12.2-1.4.5.jar                              | None                                     |
       | UCHIJAAAA | xray                                         | 1.4.0                    | xray-1.12.2-1.5.0.jar                              | None                                     |
       | UCHIJAAAA | elulib                                       | 0.1.12                   | elulib-0.1.12.jar                                  | None                                     |
       | UCHIJAAAA | teslacorelib_registries                      | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | None                                     |
  Loaded coremods (and transformers): EnderCorePlugin (EnderCore-1.12.2-0.5.41.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      ForgelinPlugin (Forgelin-1.7.4.jar)
                                        
                                      LoadingPlugin (RandomThings-MC1.12.2-4.2.1.2.jar)
                                        lumien.randomthings.asm.ClassTransformer
                                      CoreMod (Aroma1997Core-1.12.2-2.0.0.0.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      FMLPlugin (elulib-0.1.12.jar)
                                        elucent.elulib.asm.ASMTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      LoadingPlugin (Quark-r1.5-130.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      MovingWorldCore (movingworld-1.12-6.342-full.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
                                        openmods.core.OpenModsClassTransformer
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - craftingtweaksIntegration (Enabled/Not Forced)
                                   - theoneprobeIntegration (Enabled/Not Forced)
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.10.2.337
              Runtime Debofucsation 1
              RenderEngine: 0
  Ender IO: No known problems detected.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Suspected Mods: Backups (backups)
  Profiler Position: N/A (disabled)
  Player Count: 0 / 8; []
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Client Crashes Since Restart: 0
  Integrated Server Crashes Since Restart: 1

**Comment by Fadenfire** [comment]
Should be fixed in 1.4.3.
