### ISSUE TITLE
[Suggestion] Ability to delete all backups of a world at once

### ISSUE THREAD

**Issue by TheRandomLabs** [Silly511/Backups-Mod#9]
This would make testing things much more convenient.

**Comment by Fadenfire** [comment]
If you hold shift you can select multiple backups at once to delete, but something like CTRL-A to select all would be useful.

**Comment by TheRandomLabs** [comment]
Yeah, that would be great.

**Comment by Fadenfire** [comment]
In version 1.4.5 you can now use Ctrl-A to select all backups.

**Comment by TheRandomLabs** [comment]
Thanks!
